name: task_resource_manager

description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^3.2.0
  firebase_auth: ^5.1.2
  cloud_firestore: ^5.1.0
  provider: ^6.1.2
  syncfusion_flutter_calendar: ^26.1.42
  firebase_messaging: ^15.0.3
  flutter_local_notifications: ^17.2.1+2
  fl_chart: ^0.68.0
  image_picker: ^1.1.2
  intl: ^0.19.0
  table_calendar: ^3.1.2
  logger: ^1.0.0
  google_fonts: ^6.2.1
  flutter_spinkit: ^5.2.1
  fluttertoast: ^8.2.6
  animations: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
